# Generated by Django 3.0.5 on 2020-06-19 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URL_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_input', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
